#!/usr/bin/env php
<?php
require_once __DIR__ . '/../src/Cli.php';
require_once __DIR__ . '/../src/StdIO.php';
require_once __DIR__ . '/../src/Args.php';
require_once __DIR__ . '/../src/Prompt.php';
require_once __DIR__ . '/../src/Helper/TableLayout.php';
require_once __DIR__ . '/../src/Helper/Figlet.php';
require_once __DIR__ . '/../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$commands = array(
    basename(__FILE__) => array(
        'options' => array(
            /*  short  long    description
                option option */
            array('a', 'opta', 'demo description a'),
            array('b', 'optb', 'demo description b'),
            array('c', 'optc', 'demo description c')
        ),
        'helpNote' => 'This script is meant for demonstration. This script is meant for demonstration. This script is meant for demonstration. This script is meant for demonstration. This script is meant for demonstration. This script is meant for demonstration. This script is meant for demonstration. This script is meant for demonstration. This script is meant for demonstration.'
    )
);

$cli = new Cli($commands);

$cli->stdio->setAttr(array('bold'))->writeln('Hello Cli.');

$cli->bindOption('a', function($cli, $val) {
    $cli->stdio->writeln('Hello ' . $val);
});

$cli->bindOption('b', function($cli, $val) {
    $cli->stdio->writeln('Hello ' . $val);
}, array('B'));

function hello_c($cli) {
    $cli->stdio->writeln('Hello C');
}

$cli->bindOption('c', 'hello_c');

if ($cli->args->hasOption('c')) {
    hello_c($cli);
}