#!/usr/bin/env php
<?php
require_once '../src/Cli.php';
require_once '../src/StdIO.php';
require_once '../src/Args.php';
require_once '../src/Prompt.php';
require_once '../src/Helper/TableLayout.php';
require_once '../src/Helper/Figlet.php';
require_once '../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$commands = array(
    basename(__FILE__) => array(
        'helpNote' => 'This script is meant for show status demo.'
    )
);

$cli = new Cli($commands);

$cli->stdio->writeln('Welcome !');

$cli->stdio->ln();

$cli->stdio->writeln('Progress Status Demo:');
$cli->showStatus('Loading...');
sleep(5); //do some stuff---
$cli->showStatus('Loaded!', true);

$cli->stdio->ln();

$cli->stdio->writeln('Progress Count Demo:');
for ($i = 1; $i <= 10; $i++) {
    sleep(1); //do some stuff---
    $cli->showStatus('Step ' . $i, ($i == 10 ? true : false));
}

$cli->stdio->ln();

$cli->stdio->writeln('Progress Percent Demo:');
$total = 20;
$cli->showProgress($total, 0); // start
for ($i = 1; $i <= $total; $i++) {
    sleep(1); //do some stuff---
    $cli->showProgress($total, $i);
    //----------------
}

$cli->stdio->ln();

$cli->stdio->writeln('Progress Bar Demo:');
$total = 20;
$cli->showProgressBar($total, 0); // start
for ($i = 1; $i <= $total; $i++) {
    sleep(1); //do some stuff---
    $cli->showProgressBar($total, $i);
    //----------------
}

$cli->stdio->ln();
