#!/usr/bin/env php
<?php
require_once '../src/Cli.php';
require_once '../src/StdIO.php';
require_once '../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$settings = array(
    'help_note' => 'This script is meant for demonstration.'
);

$cli = new Cli($settings);

$commands = array(
    'hello' => array(
        array('a', 'opta', 'opta desc'),
        array('b', 'optb', 'optb desc')
    ),
    'world' => array()
);

$cli->promptShell('DemoShell', $commands, function ($cli, $command, $options) {
    $cli->stdio->writeln($command);
    print_r($options);
});
