#!/usr/bin/env php
<?php
require_once '../src/Cli.php';
require_once '../src/StdIO.php';
require_once '../src/Args.php';
require_once '../src/Prompt.php';
require_once '../src/TableLayout.php';
require_once '../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$settings = array(
    'commands' => array(
        basename(__FILE__) => array(
            /*  short  long    description
                option option */
            array('a', 'opta', 'demo description a'),
            array('b', 'optb', 'demo description b'),
            array('c', 'optc', 'demo description c')
        )
    ),
    'helpNote' => 'This script is meant for demonstration. script is meant for demonstration. script is meant for demonstration. script is meant for demonstration. script is meant for demonstration. script is meant for demonstration. script is meant for demonstration. script is meant for demonstration. script is meant for demonstration.'
);

$cli = new Cli($settings);

$cli->stdio->setAttr(array('bold'))->writeln('Hello Cli.');

$cli->bindOption('a', function($cli, $val) {
    $cli->stdio->writeln('Hello ' . $val);
});

$cli->bindOption('b', function($cli, $val) {
    $cli->stdio->writeln('Hello ' . $val);
}, array('B'));

function hello_c($cli) {
    $cli->stdio->writeln('Hello C');
}

$cli->bindOption('c', 'hello_c');

if ($cli->args->isOption('c')) {
    hello_c($cli);
}