#!/usr/bin/env php
<?php
require_once '../src/Cli.php';
require_once '../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$settings = array(
	'help_note' => 'This script is meant for show status demo.'
);

$cli = new Cli($settings);

$cli->cWrite('Welcome !');

$cli->nl();

$cli->cWrite('Progress Status Demo:');
$cli->showStatus('Loading...');
sleep(5);//do some stuff---
$cli->showStatus('Loaded!', true);

$cli->nl();

$cli->cWrite('Progress Count Demo:');
for($i = 1; $i <= 10; $i++){
	sleep(1);//do some stuff---
	$cli->showStatus('Step '.$i, ($i==10?true:false));
}

$cli->nl();

$cli->cWrite('Progress Percent Demo:');
$total = 20;
$cli->showProgress($total, 0); // start
for($i=1; $i<=$total; $i++){
	sleep(1);//do some stuff---
	$cli->showProgress($total, $i);
	//----------------
}

$cli->nl();

$cli->cWrite('Progress Bar Demo:');
$total = 20;
$cli->showProgressBar($total, 0); // start
for($i=1; $i<=$total; $i++){
	sleep(1);//do some stuff---
	$cli->showProgressBar($total, $i);
	//----------------
}

$cli->nl();