#!/usr/bin/env php
<?php
require_once '../src/Cli.php';
require_once '../src/StdIO.php';
require_once '../src/Args.php';
require_once '../src/Prompt.php';
require_once '../src/TableLayout.php';
require_once '../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$commands = array(
    basename(__FILE__) => array(
        'options' => array(
            array('a', 'opta', 'demo description a'),
            array('b', 'optb', 'b to stop script')
        ),
        'helpNote' => 'This script is meant for demonstration.'
    )
);

$cli = new Cli($commands);

$cli->stdio->setColor('green')->setAttr(array('bold'))->writeln('Welcome Green');
$cli->stdio->setColor('red')->setAttr(array('bold'))->writeln('Welcome Red');
$cli->stdio->hr();

if ($cli->args->isOption('b')) {
    $cli->stdio->writeln('Bye');
    $cli->stop();
}

var_dump($cli->args->isValidOption('a'));

var_dump($cli->args->hasOption('a'));

var_dump($cli->args->isOption('a'));

print_r($cli->args->get());

print_r($cli->args->getOptions('a'));

print_r($cli->args->getOptions());

$cli->stdio->setColor('red')->writeln($cli->stdio->colorizeText($cli->args->getOptionValue('a')));

$cli->stdio->ln();

$cli->stdio->writeln($cli->getMemoryUsage());
