#!/usr/bin/env php
<?php
require_once '../src/Cli.php';
require_once '../src/StdIO.php';
require_once '../src/Args.php';
require_once '../src/Prompt.php';
require_once '../src/TableLayout.php';
require_once '../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$settings = array(
    'commands' => array(
        basename(__FILE__) => array(
            /*  short  long    description
                option option */
            array('a', 'opta', 'demo description a'),
            array('b', 'optb', 'b to stop script')
        )
    ),
    'helpNote' => 'This script is meant for demonstration.'
);

$cli = new Cli($settings);

$cli->stdio->setColor('green')->setAttr(array('bold'))->writeln('Welcome Green');
$cli->stdio->setColor('red')->setAttr(array('bold'))->writeln('Welcome Red');
$cli->stdio->hr();

if ($cli->isOption('b')) {
    $cli->stdio->writeln('Bye');
    $cli->stop();
}

var_dump($cli->isValidOption('a'));

var_dump($cli->hasArg('a'));

var_dump($cli->isOption('a'));

print_r($cli->getArgs());

print_r($cli->getOptions('a'));

print_r($cli->getOptions());

$cli->stdio->setColor('red')->writeln($cli->stdio->colorizeText($cli->getOptionValue('a')));

$cli->stdio->ln();

$cli->stdio->writeln($cli->getMemoryUsage());
