#!/usr/bin/env php
<?php
require_once __DIR__ . '/../src/Cli.php';
require_once __DIR__ . '/../src/StdIO.php';
require_once __DIR__ . '/../src/Args.php';
require_once __DIR__ . '/../src/Prompt.php';
require_once __DIR__ . '/../src/Helper/TableLayout.php';
require_once __DIR__ . '/../src/Helper/Figlet.php';
require_once __DIR__ . '/../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$commands = array(
    basename(__FILE__) => array(
        'helpNote' => 'This script is meant for auth demonstration.'
    )
);

$cli = new Cli($commands);

do {
    $username = $cli->prompt->getInput('Enter Username');
    $password = $cli->prompt->getInput('Enter Password', true);
    $cli->stdio->ln();
    if ($username == 'admin' and $password == '123456') {
        $logged_in = true;
        $cli->stdio->setColor('green')->writeln('You are logged in.');
    } else {
        $logged_in = false;
        $cli->stdio->setColor('red')->writeln('Invalid Username or Password. ');
        $cli->stdio->ln();
    }
} while (!$logged_in);

$cli->stdio->ln();

$cli->stdio->writeln('Welcome !');
