#!/usr/bin/env php
<?php
require_once '../src/Cli.php';
require_once '../src/CliException.php';

use SujeetKumar\PhpCli\Cli;

$settings = array(
	'options' => array(
		array('a',    'opta',    'demo description a'),
		array('b',    'optb',    'b to stop script')
	),
	'help_note' => 'This script is meant for demonstration.'
);

$cli = new Cli($settings);

$cli->cWrite('Welcome Green', 'green');
$cli->cWrite('Welcome Red', 'red');
$cli->hr();

if($cli->isOption('b')){
	$cli->cWrite('Bye');
	$cli->stop();
}

var_dump($cli->isValidOption('a'));

var_dump($cli->hasArg('a'));

var_dump($cli->isOption('a'));

print_r($cli->getArgs());

print_r($cli->getOptions('a'));

print_r($cli->getOptions());

$cli->write($cli->colorizeText($cli->getOptionValue('a'), 'red'));

$cli->nl();

$cli->cWrite($cli->getMemoryUsage());
